// Build the function-code knowledge base from the manual text layer.
//   node tools/fc-manual/extract-text.mjs "Guiding Material/CAD Manual.pdf" tools/fc-manual/cache/manual-text.json
//   npx tsx tools/fc-manual/build-kb.ts [tools/fc-manual/cache/manual-text.json]
//
// Writes:
//   packages/function-codes/data/function_codes/NNN.json   one per manual section
//   packages/function-codes/data/manual_function_codes.json full knowledge base
//   packages/function-codes/src/generated/kb.ts             same data, importable
//   tools/fc-manual/out/kb-report.txt                       parse diagnostics
import fs from "node:fs";
import path from "node:path";
import { parseManual } from "../../packages/function-codes/src/manual-parser";
import type { ManualText } from "../../packages/function-codes/src/types";

const root = path.resolve(import.meta.dirname, "../..");
const input = process.argv[2] ?? path.join(root, "tools/fc-manual/cache/manual-text.json");
const text = JSON.parse(fs.readFileSync(input, "utf8")) as ManualText;
const kb = parseManual(text);

const dataDir = path.join(root, "packages/function-codes/data");
const fcDir = path.join(dataDir, "function_codes");
fs.rmSync(fcDir, { recursive: true, force: true });
fs.mkdirSync(fcDir, { recursive: true });
for (const fc of kb.function_codes) {
  const doc = { source: kb.source, ...fc };
  fs.writeFileSync(path.join(fcDir, `${String(fc.function_code).padStart(3, "0")}.json`), JSON.stringify(doc, null, 2) + "\n");
}
const json = JSON.stringify(kb, null, 2) + "\n";
fs.writeFileSync(path.join(dataDir, "manual_function_codes.json"), json);

const genDir = path.join(root, "packages/function-codes/src/generated");
fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(
  path.join(genDir, "kb.ts"),
  [
    "// GENERATED by tools/fc-manual/build-kb.ts from the manual text layer. Do not edit.",
    `// Source: ${kb.source.file} sha256=${kb.source.sha256}`,
    'import type { ManualKnowledgeBase } from "../types";',
    "",
    `export const KB_JSON = ${JSON.stringify(JSON.stringify(kb))};`,
    "",
    "export const KB: ManualKnowledgeBase = JSON.parse(KB_JSON) as ManualKnowledgeBase;",
    "",
  ].join("\n")
);

const report: string[] = [];
report.push(`manual: ${kb.source.file} (${kb.source.document}) pages=${kb.source.pages} sha256=${kb.source.sha256}`);
report.push(`function codes: ${kb.function_codes.length}`);
report.push(`fixed block table: ${kb.fixed_blocks ? `${kb.fixed_blocks.table} p.${kb.fixed_blocks.manual_page}, ${kb.fixed_blocks.blocks.length} rows` : "NOT FOUND"}`);
const types = new Map<string, number>();
for (const fc of kb.function_codes) for (const s of fc.specifications) types.set(s.type, (types.get(s.type) ?? 0) + 1);
report.push(`spec types: ${[...types.entries()].sort((a, b) => b[1] - a[1]).map(([t, n]) => `'${t}' x${n}`).join(", ")}`);
report.push("");
for (const d of kb.diagnostics) report.push(`GLOBAL ${d}`);
for (const fc of kb.function_codes) {
  report.push(`FC ${String(fc.function_code).padStart(3)} ${fc.name.padEnd(40)} specs=${String(fc.spec_count).padStart(3)} max=S${fc.max_spec_number} outputs=${fc.outputs.length} notes=${fc.notes.length} pages=${fc.manual_pages[0]}-${fc.manual_pages[fc.manual_pages.length - 1]} symbol=${fc.symbol.title ?? "-"} pins=${fc.symbol.inputs.join(",")}`);
  for (const d of fc.diagnostics) report.push(`        ! ${d}`);
}
const outDir = path.join(root, "tools/fc-manual/out");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "kb-report.txt"), report.join("\n") + "\n");
console.log(report.slice(0, 5).join("\n"));
console.log(`wrote ${kb.function_codes.length} function codes; report: tools/fc-manual/out/kb-report.txt`);
