export * from "./decoder/types";
export { decodeM1, CoverageError, DECODER_REVISION, M1_MAGIC } from "./decoder/scanner";
export { KNOWN_CLASSES } from "./decoder/records";
export { buildObjectGraph, type ObjectGraph, type GraphIssue, type ReferenceEdge, type RoleEvidence } from "./objects/graph";
export { analyzeTemplates, type TemplateReport, type TemplateInfo } from "./templates/templates";
export { loadTemplateLibrary, defaultLibraryDirs, type TemplateLibrary } from "./templates/library";
export { extractBindings, buildTagIndex, parseInstanceExpression, expandKey, type InstanceBindings, type Binding, type TagIndexEntry } from "./bindings/bindings";
export { buildLogicGraph, type LogicGraph } from "./logic/logic";
export { buildSceneGraph, type SceneGraph, type SceneNode } from "./scene/scene";
export * from "./geometry/transform";
export { layoutScene, type Layout, type DrawOp } from "./render/layout";
export { renderSvg } from "./render/svg";
export { renderPdf } from "./render/pdf";
export { svgToPng } from "./render/png";
export { fallbackPalette, resolveColor, hexOf, type Palette, type PaletteEntry } from "./render/palette";
export { loadSources, type ArchiveInventory } from "./archive/inventory";
export { analyzeM1, type M1Analysis } from "./pipeline/analyze";
export { runExtraction, summarize, type ExtractionResult, type ExtractionOptions, type FileResult, type FileSummary, type FileFailure, type GateItem, type Discrepancy } from "./pipeline/run";
export { runFiles, runSummaryFiles, packageFiles, writeFilePackage, writeOutputFiles, writeOutputPackage, type OutputFile } from "./package/writer";
export { validateAgainstReference } from "./validation/validate";
export { RULES, type FormatRule } from "./rules";
